server:
  port: 2003

spring:
  application:
    name: seata-account-service


  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: 1234
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

feign:
  hystrix:
    enabled: false

#logging:
#  level:
#    io:
#      seata: info


mybatis:
#  mapper-locations: classpath:mapper/*.xml
 mapperLocations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

logging:
  level:
    root: info
