server:
  port: 2001

spring:
  application:
    name: seata-order-service
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/seata_order
#    username: root
#    password: 1234

    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234

  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group


mybatis:
  mapper-locations: classpath:mapper/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://euraka7001.com:7001/eureka

#logging:
#  level: info
logging:
  level:
    io:
      seata: info
